### ISSUE TITLE
Ensure that your configuration directory only contains config.yaml

### ISSUE THREAD

**Issue by okwme** [cosmos/cosmos-registrar#17]
This is one of the recommendations at the bottom of the README.md however when I run `registrar update` it clones the entire `registry` repo to `~/Library/Application\ Support/cosmos/registry/registry`. Is this included in the recommendation to keep make sure that the directory only contains `config.yaml`?

**Comment by randomshinichi** [comment]
I meant that if you are experiencing problems, delete everything in the working directory other than config.yaml. Of course if it's working correctly, don't touch anything.

**Comment by okwme** [comment]
ah gotcha 👍
