### ISSUE TITLE
export converts strings to ints?

### ISSUE THREAD

**Issue by okwme** [cosmos/cosmos-registrar#18]
When I used the registry to upload a genesis file for `pooltoy-5` i copied it from the repo in order to start a local node of the blockchain. However I got a series of errors related to the sections `initial_height` and `consensus_params` where the values were represented as integers instead of strings. This caused the genesis validation to fail. When I export the genesis manually from the CLI with `pooltoy export` I see that the values are in fact strings. Why / when do they get converted to integers? One of them was even negative...

**Comment by tac0turtle** [comment]
Go std library json encoding is being used, but sdk and tendermint use proto json. You can use tendermint/libs/json or proto json to encode it correctly.

**Comment by randomshinichi** [comment]
~Try out fd980c8, it should fix the issue.~ spoke too soon

try 42645bf, should fix the issue

**Comment by nooomski** [comment]
I tested by running a local testnet of pooltoy-6 and using `registrar` as instructed. Everything worked as expected. This issue can be closed.
