### ISSUE TITLE
update() does not actually update peers.json, prints them though

### ISSUE THREAD

**Issue by randomshinichi** [cosmos/cosmos-registrar#7]
We can get the list of peers of a node. It would be useful to contact them to see if they're up. Problem is, most don't expose their 26657 RPC interface. No problem, we just set timeout of 2 seconds on the HTTP request (actually 1s is enough, we just want GET /status)

Not so experienced with goroutines and channels though.
[Here](https://github.com/apeunit/cosmos-registrar/blob/e5333bbd98106dd2717aaf2b8594c486639b9872/pkg/node/node.go#L181) I clearly close the channel in the wrong place, so the function returns earlier than it should.
It should be called by the last goroutine that contacts a peer but that doesn't work because no goroutine knows if it's the last one or not. Must be a different way of doing this.

**Comment by okwme** [comment]
maybe @alexanderbez 's node crawler implementation at https://github.com/cosmos/atlas/tree/main/server/crawl being used at https://atlas.cosmos.network/nodes would be a good example to base it off of?

I'm not sure how to handle your issue with goroutines but imagine stackoverflow or traditinal golang support channels might also be good to try: https://stackoverflow.com/questions/tagged/go

I'll post this issue in the discord as well

**Comment by randomshinichi** [comment]
Fixed with 4f3caa5f053fd487d04ef2498c9cc4867bdaeb15
